import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        pathname: '**',
      },
    ],
  },

  async redirects() {
    const notes = [
      { id: '1', destination: '/notes/1-welcome-to-lisle-cross-country' },
      { id: '2', destination: '/notes/2-summer-2025-information' },
      { id: '3', destination: '/notes/3-register-for-the-2025-cross-country-season' },
      { id: '4', destination: '/notes/4-our-2025-team-captains' },
      { id: '5', destination: '/notes/5-harvest-westminster-fall-classic-2025-results' },
      { id: '6', destination: '/notes/6-joliet-central-steelmen-2025-invite-results' },
      { id: '7', destination: '/notes/7-richard-spring-2025-results' },
      { id: '8', destination: '/notes/8-herscher-invite-2025-results' },
      { id: '9', destination: '/notes/9-mane-event-2025-results' },
      { id: '10', destination: '/notes/10-elmwood-park-tiger-invite-2025-results' },
      { id: '11', destination: '/notes/11-illinois-central-eight-conference-results' },
      { id: '12', destination: '/notes/12-moving-on-to-sectional-weekend' },
      { id: '13', destination: '/notes/13-the-first-state-qualifying-team-in-almost-20-years' },
      { id: '14', destination: '/notes/14-the-fastest-team-in-lisle-cross-country-history' },
      { id: '15', destination: '/notes/15-summer-camp-registration-is-open' },
    ];

    const noteRedirects = notes.map((note) => ({
      source: '/index.php',
      has: [
        {
          type: 'query' as const,
          key: 'id',
          value: note.id,
        },
      ],
      destination: note.destination,
      permanent: true,
    }));

    const runners = [
      { id: '3', slug: '3-rose-helderle' },
      { id: '4', slug: '4-calla-holik' },
      { id: '5', slug: '5-samantha-parello' },
      { id: '6', slug: '6-mirabelle-calfo' },
      { id: '7', slug: '7-violet-king' },
      { id: '8', slug: '8-cecilia-winterburn' },
      { id: '9', slug: '9-nalani-hunt' },
      { id: '10', slug: '10-audrey-martin' },
      { id: '11', slug: '11-emma-oconnor' },
      { id: '12', slug: '12-giuliana-rotelli' },
      { id: '13', slug: '13-myra-shaik' },
      { id: '14', slug: '14-sadie-shields' },
      { id: '15', slug: '15-catalina-shultes' },
      { id: '16', slug: '16-mateusz-iwanski' },
      { id: '18', slug: '18-charles-wang' },
      { id: '19', slug: '19-bequer-zamarripa' },
      { id: '20', slug: '20-konrad-fleks' },
      { id: '21', slug: '21-avery-gornick' },
      { id: '22', slug: '22-liam-marquez' },
      { id: '23', slug: '23-evan-ringsrud' },
      { id: '24', slug: '24-braylon-carey' },
      { id: '25', slug: '25-luke-erickson' },
      { id: '26', slug: '26-logan-jezewski' },
      { id: '27', slug: '27-steven-king' },
      { id: '28', slug: '28-jackson-lum-melehan' },
      { id: '29', slug: '29-carson-thomas' },
      { id: '30', slug: '30-katarina-cappel' },
      { id: '31', slug: '31-elliott-parks' },
      { id: '32', slug: '32-elizabeth-black' },
      { id: '33', slug: '33-lila-helderle' },
      { id: '34', slug: '34-olivia-kowal' },
      { id: '35', slug: '35-hylie-woodhouse' },
      { id: '36', slug: '36-isla-fundakowski' },
      { id: '37', slug: '37-heidi-kutkoski' },
      { id: '38', slug: '38-mj-melsbakas' },
      { id: '39', slug: '39-carla-ortiz-caballero' },
      { id: '40', slug: '40-lyla-swanson' },
      { id: '41', slug: '41-lena-walker' },
      { id: '42', slug: '42-blake-madsen' },
      { id: '43', slug: '43-andrew-tumbarelli' },
      { id: '44', slug: '44-maxfield-peng' },
      { id: '45', slug: '45-noah-zeigler' },
      { id: '46', slug: '46-lucas-barajas' },
      { id: '47', slug: '47-isaac-berry' },
      { id: '48', slug: '48-logan-diya' },
      { id: '49', slug: '49-sebastian-iwanski' },
      { id: '50', slug: '50-christopher-jasinski' },
      { id: '51', slug: '51-seth-keele' },
      { id: '52', slug: '52-bradley-kwak' },
      { id: '53', slug: '53-michael-parks' },
      { id: '54', slug: '54-james-pupillo' },
      { id: '55', slug: '55-jethro-thomas' },
      { id: '56', slug: '56-joseph-winterburn' },
      { id: '57', slug: '57-bastian-zamarripa' },
      { id: '58', slug: '58-anya-kutkoski' },
      { id: '59', slug: '59-belal-harb' },
      { id: '60', slug: '60-caden-carnes' },
      { id: '61', slug: '61-colin-ruthe' },
      { id: '62', slug: '62-eli-carson' },
      { id: '63', slug: '63-katie-sims' },
      { id: '64', slug: '64-max-foursayev' },
      { id: '65', slug: '65-piper-waggoner' },
      { id: '66', slug: '66-zeke-gonzalez' },
      { id: '67', slug: '67-aiden-slehofer' },
      { id: '68', slug: '68-dani-erickson' },
      { id: '69', slug: '69-eva-calcaterra' },
      { id: '70', slug: '70-jimmy-mullen' },
      { id: '71', slug: '71-molly-martin' },
      { id: '72', slug: '72-simon-klein' },
      { id: '73', slug: '73-jennifer-duban' },
      { id: '74', slug: '74-liam-newton' },
      { id: '75', slug: '75-lincoln-calfo' },
      { id: '76', slug: '76-madi-madsen' },
      { id: '77', slug: '77-cayden-denhart' },
      { id: '78', slug: '78-tre-hama-rashid' },
      { id: '79', slug: '79-avery-ardizzone' },
      { id: '80', slug: '80-morgan-craven' },
      { id: '81', slug: '81-riley-flores' },
      { id: '82', slug: '82-mallory-klein' },
      { id: '83', slug: '83-eleena-krueger' },
      { id: '84', slug: '84-lenox-lauritzen' },
      { id: '85', slug: '85-mackenzie-marks' },
      { id: '86', slug: '86-laney-martin' },
      { id: '87', slug: '87-lydai-meindle' },
      { id: '88', slug: '88-mya-most' },
      { id: '89', slug: '89-scarlett-offord' },
      { id: '90', slug: '90-lidia-ogle' },
      { id: '91', slug: '91-beatrix-paley' },
      { id: '92', slug: '92-eleanor-reese' },
      { id: '93', slug: '93-harper-russell' },
      { id: '94', slug: '94-grayson-smith' },
      { id: '95', slug: '95-mariam-syed' },
      { id: '96', slug: '96-kendall-thome' },
      { id: '97', slug: '97-ella-tumbarelli' },
      { id: '98', slug: '98-vaughn-walkowiak' },
      { id: '99', slug: '99-mira-watkins' },
      { id: '100', slug: '100-alexandra-zeman' },
      { id: '101', slug: '101-wesley-albanese' },
      { id: '102', slug: '102-tyler-lin' },
      { id: '103', slug: '103-matteo-morales' },
      { id: '104', slug: '104-ethan-black' },
      { id: '105', slug: '105-joshua-ding' },
      { id: '106', slug: '106-noah-duban' },
      { id: '107', slug: '107-abeezar-husain' },
      { id: '108', slug: '108-aj-ibrahim' },
      { id: '109', slug: '109-rafael-llanes' },
      { id: '110', slug: '110-willie-mckeever' },
      { id: '111', slug: '111-nicky-moore' },
      { id: '112', slug: '112-jackson-potjeau' },
      { id: '113', slug: '113-dylan-puzon' },
      { id: '114', slug: '114-ethan-ramirez' },
      { id: '115', slug: '115-liam-vanscoy' },
      { id: '116', slug: '116-kalsey-nano' },
    ];

    const runnerRedirects = runners.map((runner) => ({
      source: '/records.php',
      has: [
        {
          type: 'query' as const,
          key: 'runner',
          value: runner.id,
        },
      ],
      destination: `/runners/${runner.slug}`,
      permanent: true, // 301 Redirect for SEO
    }));

    // Return the dynamic runners, notes PLUS the 4 static pages
    return [
      ...noteRedirects,
      ...runnerRedirects,
      { source: '/faq.php', destination: '/faq', permanent: true },
      { source: '/schedule.php', destination: '/schedule', permanent: true },
      { source: '/results.php', destination: '/results', permanent: true },
      { source: '/results.php', destination: '/results', permanent: true },
      // This catches anyone going to records.php WITHOUT a runner ID or the index page without an ID
      { source: '/records.php', destination: '/records', permanent: true }, 
      { source: '/index.php', destination: '/', permanent: true },
    ];
  },
};

export default nextConfig;